### PR TITLE
Resolves #45. Slack notifications from AppVeyor.

### LINKED ISSUE #45: AppVeyor/Slack integration
Similar to #44, I believe I'm the only one who gets notified when the AppVeyor build breaks. However, haven't looked into what all might be involved in this yet.

Still, now that we have two guys actively contributing to the project, it would be great to get this going sooner than later to smooth out communication.

### PR DESCRIPTION
**Pull request by mjgpy3**
Same as with Travis... Not totally sure if this will work, but here goes!

### CODE REVIEW

**Comment by mjgpy3** [comment]
@Kazark any chance you could try to add your token?

**Comment by Kazark** [comment]
Yeah, sorry, meant to get to this yesterday but didn't. Will work on it at the F# brown bag today.

**Comment by Kazark** [comment]
I don't know why, but it seems the `appveyor.yml` was breaking the build. However, using what you had started,  I was able to figure out how to configure that through the UI and I think it should be working for all branches now even with out the `appveyor.yml`. I think I'll try pushing up the `appveyor.yml` it created though just to see if that will fix the build.

**Comment by Kazark** [comment]
Line endings. I think it was line endings. I downloaded the file this time instead of copying it. Windows, I hate you sometimes!

I'm going to do a squash merge of this, so I'm going to close the PR.

**Comment by Kazark** [comment]
Thanks for your work on this @mjgpy3 . Sorry I sent you on a bit of a wild goose chase since you didn't have my API key.

**Comment by mjgpy3** [comment]
Dude! I generated a commit that `unix2dos`-d that file and was ready to push it! I decided that the error seemed too unrelated, and that since YAML is very unix-y the line endings wouldn't (shouldn't) be the problem.

Haha, whoops!

**Pull request closed without merging**
