### PR TITLE
Build Void with FAKE!! The way it should be.

### PR DESCRIPTION
**Pull request by Kazark**
Need to add a `build.bat` or `build.ps1` for Windows at some point.

Also might be good to have Travis and AppVeyor kick off the FAKE build if possible.

### CODE REVIEW

**Comment by Kazark** [comment]
Accidentally deleted the wrong branch!

**Comment by Kazark** [comment]
Hm, not 100% sure this is working with AppVeyor. Going to go ahead and merge as part of that experiment. I think I might have screwed AppVeyor when I did a `git push --force` to cover up the fact that I had a commit message titled&mdash;yes, this is not a joke&mdash;`;q!`.

**Comment by Kazark** [comment]
Can't do anything right tonight.

**Comment by mjgpy3** [comment]
Very cool.

**Pull request merged**
